package com.company;

import javax.swing.*;

public class AudioGUI {
    private JButton setDirectoryButton;
    private JTextField textField1;
    private JList list1;
    private JSlider slider1;
    private JSlider slider2;
    private JSlider slider3;
    private JSlider slider4;
    private JSlider slider5;
    private JSlider slider6;
    private JSlider slider7;
    private JSlider slider8;
    private JSlider slider9;
    private JSlider slider10;
    private JSlider slider11;
    private JSlider slider12;
    private JSlider slider13;
    private JSlider slider14;
    private JSlider slider15;
    private JSlider slider16;
    private JSlider slider17;
    private JSlider slider18;
    private JSlider slider19;
    private JSlider slider20;
    private JSlider slider21;
    private JSlider slider22;
    private JSlider slider23;
    private JSlider slider24;
    private JSlider slider25;
    private JSlider slider26;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JTextField textField5;
    private JTextField textField6;
    private JTextField textField7;
    private JTextField textField8;
    private JTextField textField9;
    private JTextField textField10;
    private JTextField textField11;
    private JTextField textField12;
    private JTextField textField13;
    private JTextField textField14;
    private JTextField textField15;
    private JTextField textField16;
    private JTextField textField17;
    private JTextField textField18;
    private JTextField textField19;
    private JTextField textField20;
    private JTextField textField21;
    private JTextField textField22;
    private JTextField textField23;
    private JTextField textField24;
    private JTextField textField25;
    private JTextField textField26;
    private JTextField textField27;
    private JButton muteButton;
    private JButton muteButton1;
    private JButton muteButton4;
    private JButton muteButton5;
    private JButton muteButton7;
    private JButton restartSongButton;
}
